[tool.poetry]
name = "sendletters"
version = "0.1.0"
description = ""
authors = ["BenzhaminKim <dudgnl37@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
